// src/components/RisultatiDashboard.js
import React, { useContext } from 'react';
import { AnalysisContext } from '../context/AnalysisContext';
import { Paper, Typography, Box, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Alert, ToggleButtonGroup, ToggleButton, Divider } from '@mui/material';

// --- FUNZIONI HELPER PER LA FORMATTAZIONE ---
const formatCurrency = (value) => {
  if (typeof value !== 'number' || !isFinite(value)) return 'N/A';
  return new Intl.NumberFormat('it-IT', { style: 'currency', currency: 'EUR' }).format(value);
};
const formatNumber = (value, decimals = 2) => {
  if (typeof value !== 'number' || !isFinite(value)) return 'N/A';
  return value.toFixed(decimals);
};
const formatPercentage = (value) => {
  if (typeof value !== 'number' || !isFinite(value)) return 'N/A';
  return `${value.toFixed(2)} %`;
};

// --- COMPONENTE PRINCIPALE ---
function RisultatiDashboard() {
  const { state, dispatch } = useContext(AnalysisContext);

  const handleViewChange = (type, newView) => {
    if (newView !== null) dispatch({ type: 'SET_ACTIVE_VIEW', payload: { type, view: newView } });
  };

  if (!state.risultati) return null;
  if (!state.risultati.spFinanziario.quadratura) {
    return <Alert severity="error" sx={{ mt: 4 }}>Errore di quadratura nello Stato Patrimoniale Finanziario. Controllare i dati inseriti.</Alert>;
  }

  const { spFinanziario, spFunzionale, spMisto, ceValoreAggiunto, ceCostoVenduto, ceMargineContributo, indiciCompleti } = state.risultati;

  return (
    <Paper elevation={3} sx={{ padding: { xs: 1, sm: 3 }, borderRadius: 2 }}>
      <Typography variant="h5" component="h2" gutterBottom>Risultati dell'Analisi</Typography>
      
      <Box sx={{ my: 4 }}>
        <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2, flexWrap: 'wrap', gap: 2 }}>
          <Typography variant="h6" component="h3">Stato Patrimoniale Riclassificato</Typography>
          <ToggleButtonGroup color="primary" value={state.vistaAttiva.sp} exclusive onChange={(e, view) => handleViewChange('sp', view)}>
            <ToggleButton value="misto">Misto</ToggleButton>
            <ToggleButton value="finanziario">Finanziario</ToggleButton>
            <ToggleButton value="funzionale">Funzionale</ToggleButton>
          </ToggleButtonGroup>
        </Box>
        {state.vistaAttiva.sp === 'misto' && spMisto && (<TableContainer component={Paper}><Table size="small"><TableHead><TableRow><TableCell sx={{fontWeight: 'bold'}}>CAPITALE INVESTITO</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>Valore</TableCell><TableCell sx={{fontWeight: 'bold'}}>FONTI DI COPERTURA</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>Valore</TableCell></TableRow></TableHead><TableBody><TableRow><TableCell sx={{pl:2}}>Attivo Corrente Caratteristico</TableCell><TableCell align="right">{formatCurrency(spMisto.attivoCorrenteCaratteristico)}</TableCell><TableCell></TableCell><TableCell></TableCell></TableRow><TableRow><TableCell sx={{pl:4}}>- Passivo Corrente Caratteristico</TableCell><TableCell align="right">{formatCurrency(spMisto.passivoCorrenteCaratteristico)}</TableCell><TableCell></TableCell><TableCell></TableCell></TableRow><TableRow sx={{backgroundColor: '#f0f0f0'}}><TableCell sx={{fontWeight: 'bold'}}>= Capitale Circolante Netto Caratt. (CCNC)</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>{formatCurrency(spMisto.CCNC)}</TableCell><TableCell sx={{fontWeight: 'bold'}}>Posizione Finanziaria Netta (PFN)</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>{formatCurrency(spMisto.PFN)}</TableCell></TableRow><TableRow><TableCell sx={{pl:2}}>+ Attivo Immobilizzato Netto</TableCell><TableCell align="right">{formatCurrency(spMisto.attivoImmobilizzatoNetto)}</TableCell><TableCell sx={{pl:2}}>Patrimonio Netto</TableCell><TableCell align="right">{formatCurrency(spMisto.patrimonioNetto)}</TableCell></TableRow><TableRow sx={{borderTop: '2px solid black', backgroundColor: '#e0e0e0'}}><TableCell sx={{fontWeight: 'bold'}}>TOTALE CAPITALE INVESTITO</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>{formatCurrency(spMisto.capitaleInvestito)}</TableCell><TableCell sx={{fontWeight: 'bold'}}>TOTALE FONTI DI COPERTURA</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>{formatCurrency(spMisto.fontiDiCopertura)}</TableCell></TableRow></TableBody></Table></TableContainer>)}
        {state.vistaAttiva.sp === 'finanziario' && spFinanziario && (<TableContainer component={Paper}><Table size="small"><TableHead><TableRow><TableCell sx={{fontWeight: 'bold'}}>IMPIEGHI</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>Valore</TableCell><TableCell sx={{fontWeight: 'bold'}}>FONTI</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>Valore</TableCell></TableRow></TableHead><TableBody><TableRow><TableCell>Liquidità Immediate (LI)</TableCell><TableCell align="right">{formatCurrency(spFinanziario.aggregati.LI)}</TableCell><TableCell>Passività Correnti (PC)</TableCell><TableCell align="right">{formatCurrency(spFinanziario.aggregati.PC)}</TableCell></TableRow><TableRow><TableCell>Liquidità Differite (LD)</TableCell><TableCell align="right">{formatCurrency(spFinanziario.aggregati.LD)}</TableCell><TableCell>Passività Consolidate (Pml)</TableCell><TableCell align="right">{formatCurrency(spFinanziario.aggregati.Pml)}</TableCell></TableRow><TableRow><TableCell>Rimanenze (R)</TableCell><TableCell align="right">{formatCurrency(spFinanziario.aggregati.R)}</TableCell><TableCell sx={{fontWeight: 'bold'}}>TOTALE DEBITI</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>{formatCurrency(spFinanziario.aggregati.PC + spFinanziario.aggregati.Pml)}</TableCell></TableRow><TableRow sx={{backgroundColor: '#f0f0f0'}}><TableCell sx={{fontWeight: 'bold'}}>ATTIVO CORRENTE (AC)</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>{formatCurrency(spFinanziario.aggregati.AC)}</TableCell><TableCell></TableCell><TableCell></TableCell></TableRow><TableRow><TableCell>Attivo Immobilizzato (AI)</TableCell><TableCell align="right">{formatCurrency(spFinanziario.aggregati.AI)}</TableCell><TableCell>Capitale Netto (CN)</TableCell><TableCell align="right">{formatCurrency(spFinanziario.aggregati.CN)}</TableCell></TableRow><TableRow sx={{borderTop: '2px solid black', backgroundColor: '#e0e0e0'}}><TableCell sx={{fontWeight: 'bold'}}>TOTALE IMPIEGHI (CI)</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>{formatCurrency(spFinanziario.aggregati.CI)}</TableCell><TableCell sx={{fontWeight: 'bold'}}>TOTALE FONTI (CF)</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>{formatCurrency(spFinanziario.aggregati.CF)}</TableCell></TableRow></TableBody></Table></TableContainer>)}
        {state.vistaAttiva.sp === 'funzionale' && spFunzionale && (<TableContainer component={Paper}><Table size="small"><TableHead><TableRow><TableCell sx={{fontWeight: 'bold'}}>IMPIEGHI</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>Valore</TableCell><TableCell sx={{fontWeight: 'bold'}}>FONTI</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>Valore</TableCell></TableRow></TableHead><TableBody><TableRow><TableCell sx={{pl:2}}>Impieghi Caratteristici Correnti</TableCell><TableCell align="right">{formatCurrency(spFunzionale.impieghiCaratteristiciCorrenti)}</TableCell><TableCell sx={{pl:2}}>Fonti Correnti Caratteristiche</TableCell><TableCell align="right">{formatCurrency(spFunzionale.fontiCorrentiCaratteristiche)}</TableCell></TableRow><TableRow><TableCell sx={{pl:2}}>Impieghi Caratteristici Fissi</TableCell><TableCell align="right">{formatCurrency(spFunzionale.impieghiCaratteristiciFissi)}</TableCell><TableCell></TableCell><TableCell></TableCell></TableRow><TableRow sx={{backgroundColor: '#f0f0f0'}}><TableCell sx={{fontWeight: 'bold'}}>= Capitale Investito Caratteristico</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>{formatCurrency(spFunzionale.capitaleInvestitoCaratteristico)}</TableCell><TableCell sx={{fontWeight: 'bold'}}>= Capitale Circolante Netto Caratt. (CCNC)</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>{formatCurrency(spFunzionale.CCNC)}</TableCell></TableRow><TableRow><TableCell sx={{pl:2}}>+ Impieghi Accessori</TableCell><TableCell align="right">{formatCurrency(spFunzionale.impieghiAccessori)}</TableCell><TableCell></TableCell><TableCell></TableCell></TableRow><TableRow sx={{borderTop: '2px solid black', backgroundColor: '#e0e0e0'}}><TableCell sx={{fontWeight: 'bold'}}>TOTALE CAPITALE INVESTITO NETTO</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>{formatCurrency(spFunzionale.capitaleInvestitoNetto)}</TableCell><TableCell sx={{fontWeight: 'bold'}}>TOTALE CAPITALE ACQUISITO</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>{formatCurrency(spFunzionale.capitaleAcquisito)}</TableCell></TableRow><TableRow><TableCell></TableCell><TableCell></TableCell><TableCell sx={{pl:2}}>di cui Patrimonio Netto</TableCell><TableCell align="right">{formatCurrency(spFunzionale.patrimonioNetto)}</TableCell></TableRow><TableRow><TableCell></TableCell><TableCell></TableCell><TableCell sx={{pl:2}}>di cui Debiti Finanziari</TableCell><TableCell align="right">{formatCurrency(spFunzionale.debitiFinanziari)}</TableCell></TableRow></TableBody></Table></TableContainer>)}
      </Box>

      <Divider sx={{ my: 4 }} />

      <Box sx={{ my: 4 }}>
        <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2, flexWrap: 'wrap', gap: 2 }}>
          <Typography variant="h6" component="h3">Conto Economico Riclassificato</Typography>
          <ToggleButtonGroup color="primary" value={state.vistaAttiva.ce} exclusive onChange={(e, view) => handleViewChange('ce', view)}>
            <ToggleButton value="valoreAggiunto">Valore Aggiunto</ToggleButton>
            <ToggleButton value="costoVenduto">Costo Venduto</ToggleButton>
            <ToggleButton value="margineContributo">Margine Contribuzione</ToggleButton>
          </ToggleButtonGroup>
        </Box>
        {state.vistaAttiva.ce === 'valoreAggiunto' && ceValoreAggiunto && (<TableContainer component={Paper}><Table size="small"><TableBody><TableRow><TableCell>Valore della Produzione</TableCell><TableCell align="right">{formatCurrency(ceValoreAggiunto.valoreProduzione)}</TableCell></TableRow><TableRow><TableCell sx={{pl:4}}>- Costi Esterni</TableCell><TableCell align="right">{formatCurrency(ceValoreAggiunto.costiEsterni)}</TableCell></TableRow><TableRow sx={{fontWeight: 'bold', backgroundColor: '#f0f0f0'}}><TableCell sx={{fontWeight: 'bold'}}>= Valore Aggiunto</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>{formatCurrency(ceValoreAggiunto.valoreAggiunto)}</TableCell></TableRow><TableRow><TableCell sx={{pl:4}}>- Costo del Personale</TableCell><TableCell align="right">{formatCurrency(parseFloat(state.datiInput.ce.costiProduzione.perPersonale.valore) || 0)}</TableCell></TableRow><TableRow sx={{fontWeight: 'bold', backgroundColor: '#f0f0f0'}}><TableCell sx={{fontWeight: 'bold'}}>= Margine Operativo Lordo (MOL)</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>{formatCurrency(ceValoreAggiunto.MOL)}</TableCell></TableRow><TableRow><TableCell sx={{pl:4}}>- Ammortamenti e Svalutazioni</TableCell><TableCell align="right">{formatCurrency(parseFloat(state.datiInput.ce.costiProduzione.ammortamentiESvalutazioni.valore) || 0)}</TableCell></TableRow><TableRow sx={{fontWeight: 'bold', backgroundColor: '#e0e0e0'}}><TableCell sx={{fontWeight: 'bold'}}>= Reddito Operativo (EBIT)</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>{formatCurrency(ceValoreAggiunto.EBIT)}</TableCell></TableRow><TableRow><TableCell sx={{pl:4}}>- Proventi / Oneri Finanziari</TableCell><TableCell align="right">{formatCurrency(ceValoreAggiunto.EBT - ceValoreAggiunto.EBIT)}</TableCell></TableRow><TableRow sx={{fontWeight: 'bold'}}><TableCell sx={{fontWeight: 'bold'}}>= Risultato prima delle Imposte (EBT)</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>{formatCurrency(ceValoreAggiunto.EBT)}</TableCell></TableRow><TableRow><TableCell sx={{pl:4}}>- Imposte sul Reddito</TableCell><TableCell align="right">{formatCurrency(parseFloat(state.datiInput.ce.imposteSulReddito) || 0)}</TableCell></TableRow><TableRow sx={{fontWeight: 'bold', borderTop: '2px solid black', backgroundColor: '#e0e0e0'}}><TableCell sx={{fontWeight: 'bold'}}>= Reddito Netto</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>{formatCurrency(ceValoreAggiunto.redditoNetto)}</TableCell></TableRow></TableBody></Table></TableContainer>)}
        {state.vistaAttiva.ce === 'costoVenduto' && ceCostoVenduto && (<TableContainer component={Paper}><Table size="small"><TableBody><TableRow><TableCell>Ricavi di Vendita</TableCell><TableCell align="right">{formatCurrency(ceCostoVenduto.ricavi)}</TableCell></TableRow><TableRow><TableCell sx={{pl:4}}>- Costo del Venduto</TableCell><TableCell align="right">{formatCurrency(ceCostoVenduto.costoDelVenduto)}</TableCell></TableRow><TableRow sx={{fontWeight: 'bold', backgroundColor: '#f0f0f0'}}><TableCell sx={{fontWeight: 'bold'}}>= Margine Lordo Industriale</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>{formatCurrency(ceCostoVenduto.margineLordoIndustriale)}</TableCell></TableRow><TableRow><TableCell sx={{pl:4}}>- Costi Commerciali e Distribuzione</TableCell><TableCell align="right">{formatCurrency(ceCostoVenduto.costiCommerciali)}</TableCell></TableRow><TableRow><TableCell sx={{pl:4}}>- Costi Amministrativi e Generali</TableCell><TableCell align="right">{formatCurrency(ceCostoVenduto.costiAmministrativi)}</TableCell></TableRow><TableRow sx={{fontWeight: 'bold', backgroundColor: '#e0e0e0'}}><TableCell sx={{fontWeight: 'bold'}}>= Reddito Operativo (EBIT)</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>{formatCurrency(ceCostoVenduto.EBIT)}</TableCell></TableRow><TableRow><TableCell sx={{pl:4}}>- Proventi / Oneri Finanziari</TableCell><TableCell align="right">{formatCurrency(ceCostoVenduto.EBT - ceCostoVenduto.EBIT)}</TableCell></TableRow><TableRow sx={{fontWeight: 'bold'}}><TableCell sx={{fontWeight: 'bold'}}>= Risultato prima delle Imposte (EBT)</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>{formatCurrency(ceCostoVenduto.EBT)}</TableCell></TableRow><TableRow><TableCell sx={{pl:4}}>- Imposte sul Reddito</TableCell><TableCell align="right">{formatCurrency(parseFloat(state.datiInput.ce.imposteSulReddito) || 0)}</TableCell></TableRow><TableRow sx={{fontWeight: 'bold', borderTop: '2px solid black', backgroundColor: '#e0e0e0'}}><TableCell sx={{fontWeight: 'bold'}}>= Reddito Netto</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>{formatCurrency(ceCostoVenduto.redditoNetto)}</TableCell></TableRow></TableBody></Table></TableContainer>)}
        {state.vistaAttiva.ce === 'margineContributo' && ceMargineContributo && (<TableContainer component={Paper}><Table size="small"><TableBody><TableRow><TableCell>Ricavi di Vendita</TableCell><TableCell align="right">{formatCurrency(ceMargineContributo.ricavi)}</TableCell></TableRow><TableRow><TableCell sx={{pl:4}}>- Costi Variabili Totali</TableCell><TableCell align="right">{formatCurrency(ceMargineContributo.costiVariabiliTotali)}</TableCell></TableRow><TableRow sx={{fontWeight: 'bold', backgroundColor: '#f0f0f0'}}><TableCell sx={{fontWeight: 'bold'}}>= Margine di Contribuzione</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>{formatCurrency(ceMargineContributo.margineContribuzione1)}</TableCell></TableRow><TableRow><TableCell sx={{pl:4}}>- Costi Fissi Totali</TableCell><TableCell align="right">{formatCurrency(ceMargineContributo.costiFissiTotali)}</TableCell></TableRow><TableRow sx={{fontWeight: 'bold', backgroundColor: '#e0e0e0'}}><TableCell sx={{fontWeight: 'bold'}}>= Reddito Operativo (EBIT)</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>{formatCurrency(ceMargineContributo.EBIT)}</TableCell></TableRow><TableRow><TableCell sx={{pl:4}}>- Proventi / Oneri Finanziari</TableCell><TableCell align="right">{formatCurrency(ceMargineContributo.EBT - ceMargineContributo.EBIT)}</TableCell></TableRow><TableRow sx={{fontWeight: 'bold'}}><TableCell sx={{fontWeight: 'bold'}}>= Risultato prima delle Imposte (EBT)</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>{formatCurrency(ceMargineContributo.EBT)}</TableCell></TableRow><TableRow><TableCell sx={{pl:4}}>- Imposte sul Reddito</TableCell><TableCell align="right">{formatCurrency(parseFloat(state.datiInput.ce.imposteSulReddito) || 0)}</TableCell></TableRow><TableRow sx={{fontWeight: 'bold', borderTop: '2px solid black', backgroundColor: '#e0e0e0'}}><TableCell sx={{fontWeight: 'bold'}}>= Reddito Netto</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>{formatCurrency(ceMargineContributo.redditoNetto)}</TableCell></TableRow></TableBody></Table></TableContainer>)}
      </Box>

      <Divider sx={{ my: 4 }} />
      
      {indiciCompleti && (<Box sx={{ my: 4 }}>
         <Typography variant="h6" component="h3" gutterBottom>Sistema Completo degli Indici di Bilancio</Typography>
        <TableContainer component={Paper}>
             <Table size="small">
                <TableHead><TableRow><TableCell sx={{fontWeight: 'bold'}}>Area di Analisi</TableCell><TableCell sx={{fontWeight: 'bold'}}>Indicatore</TableCell><TableCell align="right" sx={{fontWeight: 'bold'}}>Valore</TableCell></TableRow></TableHead>
                <TableBody>
                  <TableRow><TableCell rowSpan={6} sx={{fontWeight: 'bold', verticalAlign:'top'}}>Struttura Impieghi</TableCell><TableCell>Elasticità (AC / CI)</TableCell><TableCell align="right">{formatPercentage(indiciCompleti.struttura.elasticitaImpieghi)}</TableCell></TableRow>
                  <TableRow><TableCell>Rigidità (AI / CI)</TableCell><TableCell align="right">{formatPercentage(indiciCompleti.struttura.rigiditaImpieghi)}</TableCell></TableRow>
                  <TableRow><TableCell>Quoziente di Rigidità (AI / AC)</TableCell><TableCell align="right">{formatNumber(indiciCompleti.struttura.quozienteRigidita)}</TableCell></TableRow>
                  <TableRow><TableCell>Incidenza Imm. Materiali</TableCell><TableCell align="right">{formatPercentage(indiciCompleti.struttura.incidenzaImmMateriali)}</TableCell></TableRow>
                  <TableRow><TableCell>Incidenza Imm. Immateriali</TableCell><TableCell align="right">{formatPercentage(indiciCompleti.struttura.incidenzaImmImmateriali)}</TableCell></TableRow>
                  <TableRow><TableCell>Incidenza Imm. Finanziarie</TableCell><TableCell align="right">{formatPercentage(indiciCompleti.struttura.incidenzaImmFinanziarie)}</TableCell></TableRow>
                  
                  <TableRow><TableCell rowSpan={6} sx={{fontWeight: 'bold', verticalAlign:'top'}}>Struttura Fonti</TableCell><TableCell>Autonomia Finanziaria (CN / CI)</TableCell><TableCell align="right">{formatPercentage(indiciCompleti.fonti.autonomiaFinanziaria)}</TableCell></TableRow>
                  <TableRow><TableCell>Dipendenza Finanziaria (Debiti / CI)</TableCell><TableCell align="right">{formatPercentage(indiciCompleti.fonti.dipendenzaFinanziaria)}</TableCell></TableRow>
                  <TableRow><TableCell>Leverage (Debiti / CN)</TableCell><TableCell align="right">{formatNumber(indiciCompleti.fonti.leverage)}</TableCell></TableRow>
                  <TableRow><TableCell>Consolidamento Passivo (Pml / Debiti)</TableCell><TableCell align="right">{formatPercentage(indiciCompleti.fonti.consolidamentoPassivo)}</TableCell></TableRow>
                  <TableRow><TableCell>Solidità Patrimoniale (CN / CS)</TableCell><TableCell align="right">{formatNumber(indiciCompleti.fonti.soliditaPatrimoniale)}</TableCell></TableRow>
                  <TableRow><TableCell>Protezione Capitale Sociale (Riserve / CS)</TableCell><TableCell align="right">{formatNumber(indiciCompleti.fonti.protezioneCapitaleSociale)}</TableCell></TableRow>
                  
                  <TableRow><TableCell rowSpan={6} sx={{fontWeight: 'bold', verticalAlign:'top'}}>Liquidità e Correlazione</TableCell><TableCell>Quoziente di Disponibilità (Current Ratio)</TableCell><TableCell align="right">{formatNumber(indiciCompleti.liquidita.quozienteDisponibilita)}</TableCell></TableRow>
                  <TableRow><TableCell>Quoziente di Tesoreria (Quick Ratio)</TableCell><TableCell align="right">{formatNumber(indiciCompleti.liquidita.quozienteTesoreria)}</TableCell></TableRow>
                  <TableRow><TableCell>Margine di Struttura Primario</TableCell><TableCell align="right">{formatCurrency(indiciCompleti.liquidita.margineStrutturaPrimario)}</TableCell></TableRow>
                  <TableRow><TableCell>Margine di Struttura Secondario</TableCell><TableCell align="right">{formatCurrency(indiciCompleti.liquidita.margineStrutturaSecondario)}</TableCell></TableRow>
                  <TableRow><TableCell>Capitale Circolante Netto (CCN)</TableCell><TableCell align="right">{formatCurrency(indiciCompleti.liquidita.capitaleCircolanteNetto)}</TableCell></TableRow>
                  <TableRow><TableCell>Margine di Tesoreria</TableCell><TableCell align="right">{formatCurrency(indiciCompleti.liquidita.margineTesoreria)}</TableCell></TableRow>
                  
                  <TableRow><TableCell rowSpan={4} sx={{fontWeight: 'bold', verticalAlign:'top'}}>Redditività</TableCell><TableCell>ROE (Return on Equity)</TableCell><TableCell align="right">{formatPercentage(indiciCompleti.redditivita.ROE)}</TableCell></TableRow>
                  <TableRow><TableCell>ROI (Return on Investment)</TableCell><TableCell align="right">{formatPercentage(indiciCompleti.redditivita.ROI)}</TableCell></TableRow>
                  <TableRow><TableCell>ROS (Return on Sales)</TableCell><TableCell align="right">{formatPercentage(indiciCompleti.redditivita.ROS)}</TableCell></TableRow>
                  <TableRow><TableCell>ROA (Return on Assets)</TableCell><TableCell align="right">{formatPercentage(indiciCompleti.redditivita.ROA)}</TableCell></TableRow>
                  
                  <TableRow><TableCell rowSpan={6} sx={{fontWeight: 'bold', verticalAlign:'top'}}>Rotazione e Durata</TableCell><TableCell>Rotazione Capitale Investito</TableCell><TableCell align="right">{formatNumber(indiciCompleti.rotazione.rotazioneCI)}</TableCell></TableRow>
                  <TableRow><TableCell>Rotazione Attivo Corrente</TableCell><TableCell align="right">{formatNumber(indiciCompleti.rotazione.rotazioneAC)}</TableCell></TableRow>
                  <TableRow><TableCell>Rotazione Magazzino</TableCell><TableCell align="right">{formatNumber(indiciCompleti.rotazione.rotazioneRimanenze)}</TableCell></TableRow>
                  <TableRow><TableCell>Durata Magazzino (giorni)</TableCell><TableCell align="right">{formatNumber(indiciCompleti.rotazione.durataRimanenze, 0)}</TableCell></TableRow>
                  <TableRow><TableCell>Durata Crediti Commerciali (giorni)</TableCell><TableCell align="right">{formatNumber(indiciCompleti.rotazione.durataCrediti, 0)}</TableCell></TableRow>
                  <TableRow><TableCell>Durata Debiti Commerciali (giorni)</TableCell><TableCell align="right">{formatNumber(indiciCompleti.rotazione.durataDebiti, 0)}</TableCell></TableRow>
                </TableBody>
             </Table>
        </TableContainer>
      </Box>)}
    </Paper>
  );
}

export default RisultatiDashboard;